version: '3'
services:
  todotests:
    image: todotests
    # build: ./todo-app/tests
    # container_name: todotests
    depends_on:
      - todofront
      - todoback
    network_mode: host
  todofront:
    image: todofrontend
    # build: ./todo-app/front-end
    # container_name: todofrontend
    ports:
      - "3000:3000"
    depends_on:
      - todoback
  todoback:
    image: todobackend
    # build: ./todo-app/back-end
    # container_name: todobackend
    ports:
      - "3001:3001"
